name: flutter_my_radio
description: "Radio-browser client API. flutter_my_radio provide an easy way to find and listen any web radio in your flutter app."
version: 1.0.4
repository: https://github.com/mynumeric-mobile/flutter_my_radio

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  basic_utils: ^5.7.0
  flutter_minimalist_audio_player: ^1.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  
  plugin:
    platforms:
    
      some_platform:
        pluginClass: somePluginClass
 